In [1]:
i = 1
while i < 5:
    print('i is :{}'.format(i))
    i = i+1

i is :1
i is :2
i is :3
i is :4


In [2]:
def countDog(st):
    count = 0
    for word in st.lower().split():
        if word == 'dog':
            count += 1
    return count

In [3]:
countDog('dog is dog well')

2

In [8]:
def tomLove(st):return st[0]

In [9]:
tomLove('thomas')

't'

In [10]:
lambda num:num*2

<function __main__.<lambda>(num)>

In [13]:
lambda num:num**2

<function __main__.<lambda>(num)>

In [14]:
seq = [1,2,3,4,5]

In [23]:
l = lambda num:num**2

In [24]:
list(map(lambda num:num**2,seq))

[1, 4, 9, 16, 25]

In [27]:
l(45)

2025

In [28]:
seq = ['soup','dog','salad','cat','greet']

In [30]:
list(filter(lambda st:st[0]!='s',seq))

['dog', 'cat', 'greet']

In [32]:
list(filter(lambda st:st[0]=='s',seq))

['soup', 'salad']

In [38]:
def caught_speeding(speed,is_birthday):
    if is_birthday:
        speeding = speed-5        
    if speed > 81:
        print('big ticket')
    elif speed > 61:
        print('small ticket')
    else:
        print('no ticket')
            
        
            
            

In [39]:
caught_speeding(81,True)

small ticket


In [41]:
caught_speeding(23,True)

no ticket


numpy array 

In [42]:
my_list = [1,2,3]

In [43]:
import numpy as np

In [44]:
np.array(my_list)

array([1, 2, 3])

In [45]:
arr = np.array(my_list)

In [46]:
arr

array([1, 2, 3])

In [47]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [48]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [51]:
np.zeros((2))

array([0., 0.])

In [52]:
np.zeros(4)

array([0., 0., 0., 0.])

In [53]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.ones((2))

array([1., 1.])

In [55]:
np.ones(3)

array([1., 1., 1.])

In [56]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [59]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [62]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
np.full((2,3),33)

array([[33, 33, 33],
       [33, 33, 33]])

In [66]:
np.random.rand(5)

array([0.01267363, 0.18075485, 0.54281333, 0.04517052, 0.54236698])

In [67]:
np.random.rand(4,3)

array([[0.62509569, 0.45482525, 0.31892238],
       [0.61456146, 0.21008985, 0.2242491 ],
       [0.87094282, 0.93274733, 0.63501375],
       [0.4073264 , 0.46431247, 0.76514232]])

In [68]:
np.random.randn(2)

array([-2.19956737,  1.17118117])

In [69]:
np.random.randn(4,5)

array([[-0.67097688,  0.79935136,  1.08440325, -1.44760882,  0.69625523],
       [-0.24889168, -1.49292938, -2.20342966, -0.93228306, -0.79034516],
       [ 0.06824229, -0.95905667, -0.45141082, -0.90748577,  0.93550967],
       [-0.19460195, -1.92789127,  1.04814866,  0.86670784,  0.73975424]])

In [77]:
np.random.randint(1,100)

35

In [78]:
np.random.randint(1,100,4)

array([ 6, 23, 18, 42])

In [79]:
arr = np.arange(25)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
ranarr = np.random.randint(0,50,10)

In [82]:
ranarr

array([29, 38, 15, 47, 49,  0, 46,  5, 17, 15])

In [83]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
ranarr.max()

49

In [85]:
ranarr.min()

0

In [86]:
ranarr

array([29, 38, 15, 47, 49,  0, 46,  5, 17, 15])

In [87]:
ranarr.argmax()    

4

In [88]:
ranarr.argmin()

5

In [89]:
arr.shape

(25,)

In [91]:
arr = arr.reshape(5,5)

In [92]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
arr.shape

(5, 5)

In [94]:
arr.dtype

dtype('int32')

In [95]:
from numpy.random import randint

In [96]:
randint(2,10)

5

Numpy indexing and selection

In [97]:
import numpy as np

In [98]:
arr = np.arange(0,11)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr[8]

8

In [101]:
arr[1:5]

array([1, 2, 3, 4])

In [102]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [103]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [104]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [105]:
arr[0:5] = 100

In [106]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [107]:
arr = np.arange(0,11)

In [108]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
slice_of_arr = arr[0:6]

In [117]:
arr = np.arange(0,11)

In [118]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
slice_of_arr = arr[0:6]

In [120]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [121]:
slice_of_arr[:] = 99

In [122]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [123]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [125]:
arr_copy = arr.copy()

In [126]:
arr_copy[:] = 100

In [127]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [128]:
import numpy as np

In [129]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [130]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [131]:
arr_2d[0][0]

5

In [132]:
arr_2d[2][1]

40

In [133]:
arr_2d[2,1]

40

In [134]:
arr_2d[2][1]

40

In [135]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [136]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [137]:
arr = np.arange(1,11)

In [138]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [140]:
bool_arr = arr>5

In [141]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [142]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [143]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [144]:
arr[arr<3]

array([1, 2])

In [145]:
arr_2d = np.arange(50).reshape(5,10)

In [146]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [148]:
arr_2d[1:3,]  

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [149]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [150]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [1]:
import numpy as np

In [2]:
arr_2d = np.arange(50).reshape(5,10)  

In [3]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Numpy Operations

* array with array
* array with scalar

* Universal Array FUNCTIONS

In [4]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [11]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [12]:
arr/arr

<ipython-input-12-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
1/arr

<ipython-input-13-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.max(arr)

10

In [18]:
arr.max()

10

In [19]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [20]:
np.log(arr)

<ipython-input-20-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [1]:
### numpy solution

In [2]:
import numpy as np

In [3]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.zeros((10)) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.ones((10)) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.random(1)

array([0.78933312])

In [24]:
np.random.randn(25)

array([-1.06612689,  1.28069798,  0.94501204, -0.50256694, -0.22968481,
       -1.08058487,  0.35121385, -1.57020655,  0.28851277, -0.13199783,
        0.39055444,  2.2104098 ,  0.75300078, -0.28888357,  0.24981673,
        0.51570681, -0.79217307,  0.66431372, -1.11038945, -0.17981811,
        0.5770746 , -0.0755188 ,  0.5093062 , -0.25332808,  0.2128998 ])

In [25]:
np.random.randint(23)

19

In [29]:
np.random.random(1)

array([0.58327407])

In [36]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [37]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [39]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
mat[0:3,1]

array([ 2,  7, 12])

In [46]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [47]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
mat[4]

array([21, 22, 23, 24, 25])

In [49]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
mat.sum()

325

In [51]:
np.sum(mat)

325

In [52]:
np.std(mat)

7.211102550927978

In [53]:
mat.std()

7.211102550927978

In [54]:
np.sum(mat[1])

40

In [55]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
np.sum(mat[0])

15

exercise solution

import numpy as np  

In [58]:
import numpy as np

In [59]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
np.zeros(10) * 5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [64]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [65]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [66]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
a=np.arange(9)
a.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.random.random(1)

array([0.23721181])

In [74]:
np.random.rand(1)

array([0.8579989])

In [75]:
np.random.randn(25)

array([-0.7198242 , -0.44024704, -1.61771607,  1.58838029,  1.67213821,
       -1.03096713,  0.97703697,  0.48113652,  0.78118097, -0.36250597,
       -2.59370485,  0.50269822,  0.66722453, -0.48190964,  1.02130299,
        1.89412912, -1.94728641, -1.29510993,  0.04097672, -1.08163724,
       -0.43693853, -0.54267377,  0.18459503, -0.78426635, -1.05759606])

In [76]:
np.random.randn(25).shape    

(25,)

In [78]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [79]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [80]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [81]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
mat[2:,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
mat[2:,0:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [86]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [88]:
mat[3,4]

20

In [89]:
mat[3][4]

20

In [90]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [91]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [92]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [93]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [94]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [95]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
np.sum(mat)

325

In [97]:
mat.sum()

325

In [98]:
np.std(mat)

7.211102550927978

In [99]:
mat.std()

7.211102550927978

In [100]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [101]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [102]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])