In [1]:
import numpy as np

In [2]:
a = np.array([3,6,9,12])

In [3]:
a/3

array([1., 2., 3., 4.])

In [4]:
list1 = [2,4,6,8]

In [5]:
#list1/2

In [6]:
## NUMPY TUTORIAL

In [6]:
import numpy as np 

In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0 ],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# GET DIMENSION
a.ndim

1

In [13]:
#GET Shape
b.shape

(2, 3)

In [14]:
#GET Type
a.dtype

dtype('int32')

In [15]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [16]:
a.dtype

dtype('int16')

In [17]:
#Get Size
a.itemsize

2

In [18]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [19]:
a.itemsize

4

In [20]:
#  GET TOTAL SIZE
a.size

3

In [21]:
a.nbytes 

12

In [25]:
# acessing/changing specific elements,rows,columns,etc

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
a.shape

(2, 7)

In [24]:
a.dtype

dtype('int32')

In [25]:
a.size

14

In [26]:
a.ndim

2

In [27]:
a.nbytes

56

In [28]:
# get a specific element [r,c]
a[1,5]


13

In [29]:
a[1,-2]

13

In [30]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# get a specific column
a[:,2]

array([ 3, 10])

In [32]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [41]:
# GETTING A BIT MORE FANCY[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [42]:
a[0,1:6:2]

array([2, 4, 6])

In [44]:
a[1,1:6:2]

array([ 9, 11, 13])

In [46]:
a[1,1:6:-2]

array([], dtype=int32)

In [47]:
a[0,1:-2:2] 

array([2, 4])

In [48]:
a[0,1:-1:2]

array([2, 4, 6])

In [33]:
import numpy as np

In [34]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

a[:,5] = [100,100]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[  1   2   1   4   5 100   7]
 [  8   9   2  11  12 100  14]]


In [72]:
# 3d examples

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
# get specific element (work outside in)
b[0,1,1]

4

In [40]:
b[1,0,0]

5

In [41]:
b[0,1,:]

array([3, 4])

In [42]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [43]:
b[:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [44]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [45]:
b[:,:,:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [47]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [90]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [48]:
b[:,:,0]

array([[1, 3],
       [5, 7]])

In [92]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [93]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
b[:,0,0]

array([1, 5])

In [50]:
b[:,1,0]

array([3, 7])

In [51]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [52]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [53]:
# replace
b[:,1,:] = [[99,99],[99,99]]

In [54]:
b

array([[[ 1,  2],
        [99, 99]],

       [[ 5,  6],
        [99, 99]]])

In [55]:
# initializing diferent types of arrays

In [56]:
# ALL 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [103]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
# ALL 1s matrix
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.ones((2,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [60]:
np.ones((2,5,5),dtype='int32')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [63]:
np.full(3,5)

array([5, 5, 5])

In [108]:
# Any other number 
np.full((3,3),44)

array([[44, 44, 44],
       [44, 44, 44],
       [44, 44, 44]])

In [65]:
np.full((3,3),44,dtype='float32')

array([[44., 44., 44.],
       [44., 44., 44.],
       [44., 44., 44.]], dtype=float32)

In [66]:
a

array([[  1,   2,   1,   4,   5, 100,   7],
       [  8,   9,   2,  11,  12, 100,  14]])

In [111]:
#Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [67]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [68]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.20690329, 0.72654878],
       [0.95481357, 0.26554027],
       [0.25396608, 0.86954857],
       [0.86541499, 0.1978376 ]])

In [69]:
np.random.rand(4,2,3)

array([[[0.75184471, 0.69629126, 0.38024656],
        [0.1333061 , 0.02977891, 0.90661391]],

       [[0.05700122, 0.88230048, 0.4114083 ],
        [0.71902247, 0.57099897, 0.20727797]],

       [[0.65714757, 0.40019719, 0.98492989],
        [0.68023555, 0.33277423, 0.70155908]],

       [[0.19887726, 0.30393925, 0.14561597],
        [0.88924325, 0.52195258, 0.9652291 ]]])

In [70]:
np.random.random_sample(a.shape)

array([[0.28336105, 0.70049068, 0.86568911, 0.78001251, 0.67140249,
        0.48303941, 0.36485657],
       [0.53774794, 0.63219432, 0.57298285, 0.13520857, 0.71118009,
        0.17798214, 0.86394757]])

In [71]:
np.random.rand(4,2)

array([[0.23052615, 0.32691844],
       [0.96206029, 0.57135537],
       [0.87796908, 0.90595229],
       [0.24256781, 0.27923888]])

In [118]:
# Random integer values
np.random.randint(4,7,size=(3,4))

array([[4, 6, 4, 5],
       [5, 6, 5, 5],
       [4, 6, 6, 4]])

In [119]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [121]:
#identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [124]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [125]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [133]:
k = np.ones((5,5))
print(k)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [134]:
k[1:4,1:4]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [135]:
k[1,4]

1.0

In [149]:
tom = np.arange(25)

In [150]:
tom.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

 be careful when coping arrays!!!

a = np.array([1,2,3])
b = am


In [159]:
a = np.array([1,2,3])
b = a
b[0] = 100
a
b


array([100,   2,   3])

In [161]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


maths

In [162]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [163]:
a + 2

array([3, 4, 5, 6])

In [164]:
a - 2

array([-1,  0,  1,  2])

In [165]:
a * 2

array([2, 4, 6, 8])

In [166]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [167]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [168]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [73]:
# take the sine of all value 
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.84147098, -0.7568025 , -0.95892427,
        -0.50636564,  0.6569866 ],
       [ 0.98935825,  0.41211849,  0.90929743, -0.99999021, -0.53657292,
        -0.50636564,  0.99060736]])

In [74]:
np.cos(b)

array([[[ 0.54030231, -0.41614684],
        [ 0.03982088,  0.03982088]],

       [[ 0.28366219,  0.96017029],
        [ 0.03982088,  0.03982088]]])

linear algebra

In [171]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [172]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

statistics

In [75]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.min(stats,axis=1)

array([1, 4])

In [78]:
np.max(stats,axis=0)

array([4, 5, 6])

In [175]:
np.min(stats)

1

In [176]:
np.max(stats) 

6

In [177]:
np.max(stats,axis=1)

array([3, 6])

In [178]:
np.max(stats,axis=0)

array([4, 5, 6])

In [79]:
np.sum(stats)

21

In [80]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
np.sum(stats,axis=1)

array([ 6, 15])

In [81]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [184]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [187]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((2,2,2))
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
import numpy as np

In [3]:
#Vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [4]:
#horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))



array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [5]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [6]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Miscellananeous 
Load Data from File

In [1]:
pwd

'C:\\Users\\Engr. Tom\\Data_science_file'

In [2]:
import numpy as np

In [86]:
np.genfromtxt('data.txt',delimiter=',')

array([[ 1., 13., 45., 67.,  7.,  8.,  3.,  5.,  6.,  7.,  8.,  9.,  6.],
       [12., 23.,  2., 12., 13., 12., 56., 76., 89., 66., 10., 15., 14.],
       [ 3., 12., 45., 67., 89., 56., 45., 78., 89., 89., 76., 89., 20.]])

In [87]:
import numpy as np

In [88]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata.astype('int32')
filedata



array([[ 1., 13., 45., 67.,  7.,  8.,  3.,  5.,  6.,  7.,  8.,  9.,  6.],
       [12., 23.,  2., 12., 13., 12., 56., 76., 89., 66., 10., 15., 14.],
       [ 3., 12., 45., 67., 89., 56., 45., 78., 89., 89., 76., 89., 20.]])

###### Advanced index
boolean masking and Advanced indexing


In [89]:
import numpy as np

In [90]:
filedata > 50

array([[False, False, False,  True, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True,
         True, False, False, False],
       [False, False, False,  True,  True,  True, False,  True,  True,
         True,  True,  True, False]])

In [91]:
filedata[filedata>50]

array([67., 56., 76., 89., 66., 67., 89., 56., 78., 89., 89., 76., 89.])

In [18]:
## You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [92]:
filedata

array([[ 1., 13., 45., 67.,  7.,  8.,  3.,  5.,  6.,  7.,  8.,  9.,  6.],
       [12., 23.,  2., 12., 13., 12., 56., 76., 89., 66., 10., 15., 14.],
       [ 3., 12., 45., 67., 89., 56., 45., 78., 89., 89., 76., 89., 20.]])

In [19]:
np.any(filedata>50,axis=0)

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False])

In [20]:
np.all(filedata>50,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [21]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [22]:
((filedata>50)&(filedata<100)) 

array([[False, False, False,  True, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True,
         True, False, False, False],
       [False, False, False,  True,  True,  True, False,  True,  True,
         True,  True,  True, False]])

In [23]:
(~((filedata>50) &(filedata<100)))

array([[ True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False, False, False,
        False,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True, False, False,
        False, False, False,  True]])

PYTHON CRASH COURSE

In [24]:
1

1

In [25]:
1.0

1.0

In [26]:
1 * 3

3

In [27]:
1/2.0

0.5

In [28]:
2**4

16

In [29]:
2+3*5+5

22

In [30]:
 (2+3) * (5+5)

50

In [31]:
4%2

0

In [32]:
5%2

1

In [33]:
8%2

0

In [34]:
Var = 2

In [36]:
Var

2

In [37]:
x = 2
y = 3

In [38]:
x+y

5

In [39]:
x = x+x

In [40]:
x

4

In [41]:
12var

SyntaxError: invalid syntax (<ipython-input-41-f1ac9495ba0b>, line 1)

In [42]:
!var = 12

'var' is not recognized as an internal or external command,
operable program or batch file.


In [43]:
name_of_school = 'high school'

In [44]:
#strings

In [45]:
'this is a string'

'this is a string'

In [46]:
"this is a string"

'this is a string'

In [47]:
"i can't go"

"i can't go"

In [48]:
x = "hello"

In [49]:
print(x)

hello


In [50]:
num=12
name = 'Sam'


In [51]:
'My number is {} and my name is {}'.format(num,name)

'My number is 12 and my name is Sam'

In [52]:
'My number is {one} and my name is {two}'.format(one=num,two=name)

'My number is 12 and my name is Sam'

In [53]:
print('My number is {one} and my name is {two}'.format(one=num,two=name))

My number is 12 and my name is Sam


In [54]:
print('My number is {one} and my name is {two},more{one}'.format(one=num,two=name))

My number is 12 and my name is Sam,more12


In [55]:
s = 'hello'

In [56]:
s

'hello'

In [57]:
s[0]

'h'

In [58]:
s[4]

'o'

In [60]:
s = 'abcdefghijk'

In [62]:
s[0:]

'abcdefghijk'

In [63]:
s[:3]

'abc'

In [64]:
s[0:3]

'abc'

In [65]:
s[3:6]

'def'

In [66]:
[1,2,3]

[1, 2, 3]

In [67]:
['a','b','c']

['a', 'b', 'c']

In [68]:
my_list = ['a','b','c']

In [69]:
my_list.append('d')

In [70]:
my_list

['a', 'b', 'c', 'd']

In [71]:
my_list[0]

'a'

In [72]:
my_list[1:3]

['b', 'c']

In [73]:
my_list[0] = 'NEW'

In [74]:
my_list

['NEW', 'b', 'c', 'd']

In [75]:
nest = [1,2,[3,4]]

In [76]:
nest

[1, 2, [3, 4]]

In [77]:
nest[2]

[3, 4]

In [78]:
 nest[2][1]

4

In [79]:
nest = [1,2,3,[4,5,['target']]]

In [80]:
print(nest[3][2][0])

target


In [90]:
## dictionary

In [81]:
d = {'key1':'value','key2':123}

In [82]:
d['key1']

'value'

In [83]:
d['key2']

123

In [84]:
d = {'k1':[1,2,3]}

In [85]:
d['k1']

[1, 2, 3]

In [86]:
d['k1'][2]

3

In [87]:
my_list = d['k1']

In [88]:
my_list

[1, 2, 3]

In [89]:
my_list[0]

1

In [91]:
d = {'k1':{'innerkey':[1,2,3]}}

In [93]:
d['k1']['innerkey']

[1, 2, 3]

In [94]:
d['k1']['innerkey'][1]

2

In [95]:
## boolean

In [96]:
True

True

In [97]:
False

False

In [98]:
my_list = [1,2,3]

In [99]:
my_list[0]

1

In [100]:
t = (1,2,3)

In [101]:
t[0]

1

In [102]:
my_list[0] = 'NEW'

In [104]:
t[0] = 'NEW'

TypeError: 'tuple' object does not support item assignment

In [105]:
{1,2,3}

{1, 2, 3}

In [106]:
{1,1,1,2,2,2,3,3,3}

{1, 2, 3}

In [107]:
set([1,1,1,1,2,2,2,5,5,6,6,6])

{1, 2, 5, 6}

In [108]:
s = {1,2,3}

In [109]:
s.add(5)

In [110]:
s

{1, 2, 3, 5}

In [111]:
### comprahesive operator

In [112]:
1 > 2

False

In [113]:
1<2

True

In [114]:
1 <= 2

True

In [115]:
1 == 1

True

In [116]:
1==2

False

In [117]:
1 != 3

True

In [118]:
'hi' == 'bye'

False

In [119]:
'hi' != 'bye'

True

In [120]:
1 < 2 and 2 < 3

True

In [122]:
(1 < 2) and (2 > 3)

False

In [123]:
(1<2) or (2>3)

True

In [124]:
(1<2) or (2>3) or (1==1)

True

In [125]:
True and True

True

In [126]:
True and False

False

In [127]:
if 1<2:
    print('yep!')

yep!


In [128]:
if True:
    print('perform Code')

perform Code


In [129]:
if True:
    x = 2+2

In [130]:
x

4

In [131]:
if 1 == 2:
    print('first')
else:
    print('last')

last


In [132]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('last')

middle


In [133]:
if 1 == 2:
    print('first')
elif 4==4:
    print('second')
elif 3 == 3:
    print('middle')
else:
    print('last')

second


In [134]:
### for loop

In [135]:
seq = [1,2,3,4,5]

In [136]:
for item in seq:
    print(item)

1
2
3
4
5


In [137]:
for num in seq:
    print(num)

1
2
3
4
5


In [139]:
for num in seq:
    print('hello')

hello
hello
hello
hello
hello


In [140]:
##while loop  

In [141]:
i = 1
while i < 5:
    print('i is :{}'.format(i))
    i = i+1

i is :1
i is :2
i is :3
i is :4


In [142]:
for x in seq:
    print(x)

1
2
3
4
5


In [143]:
### range function

In [144]:
 for x in range(0,5):
        print(x)

0
1
2
3
4


In [145]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [146]:
x = [1,2,3,4]

In [147]:
out=[]
for num in x:
    out.append(num**2)

In [148]:
print(out)

[1, 4, 9, 16]


In [149]:
[num**2 for num in x]

[1, 4, 9, 16]

In [151]:
out = [num**2 for num in x]

In [152]:
out

[1, 4, 9, 16]

In [155]:
### defining of function

In [156]:
def my_func(param1):
    print(param1)

In [157]:
my_func('hello')

hello


In [158]:
def my_func(name):
    print('Hello' +name)

In [161]:
my_func('tom')


Hellotom


In [163]:
def my_func(name='Default Name'):
    print('hello' +name)

In [164]:
my_func()

helloDefault Name


In [165]:
def square(num):
    return num**2

In [166]:
square(2)

4

In [168]:
def times2(var):
    return var*2

In [169]:
times2(4)

8

In [178]:
## map()

In [179]:
seq = [1,2,3,4,5]

In [180]:
map(times2,seq)

In [181]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [184]:
#lambda expression

In [185]:
lambda var:var*2

<function __main__.<lambda>(var)>

In [186]:
t = lambda var:var*2

In [187]:
t(2)

4

In [188]:
seq = [1,2,3,4,5,6,7,8]

In [189]:
list(map(lambda num:num*2,seq))

[2, 4, 6, 8, 10, 12, 14, 16]

In [190]:
list(filter(lambda num:num%2==0,seq))

[2, 4, 6, 8]

In [191]:
s = 'hello my name is Sam'

In [192]:
s.lower()

'hello my name is sam'

In [193]:
s.upper()

'HELLO MY NAME IS SAM'

In [194]:
s.split()

['hello', 'my', 'name', 'is', 'Sam']

In [195]:
tweet = 'Go Sports! #Sports'

In [196]:
tweet.split()

['Go', 'Sports!', '#Sports']

In [198]:
tweet.split('#')

'Sports'

In [199]:
tweet.split('#')[1]

'Sports'

In [200]:
d = {'k1':1,'k2':2}

In [201]:
d

{'k1': 1, 'k2': 2}

In [202]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [203]:
d.keys()

dict_keys(['k1', 'k2'])

In [204]:
d.values()

dict_values([1, 2])

In [205]:
lst = [1,2,3]

In [206]:
lst.pop()

3

In [207]:
lst

[1, 2]

In [208]:
lst = [1,2,3,4,5]

In [209]:
item=lst.pop()

In [210]:
item

5

In [211]:
first = lst.pop(0)

In [212]:
lst

[2, 3, 4]

In [213]:
first

1

In [214]:
'x' in [1,2,3]

False

In [216]:
x = [(1,2),(3,4),(5,6)]

In [217]:
for item in x:
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [218]:
for (a,b) in x:
    print(a)

1
3
5


In [219]:
for a,b in x:
    print(b)

2
4
6


EXERCISE PYTHON CRASH COURSE

In [220]:
7**4

2401

In [223]:
s = 'Hi there Sam!'
s.split()

['Hi', 'there', 'Sam!']

In [226]:
w = 'Hi there dad!'
w.split()

['Hi', 'there', 'dad!']

In [227]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [233]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [236]:
# difference bet. tuple and list
#tuple is immutable and list is mutable

In [239]:
def domainGet(var):
    return var[5:]

In [240]:
domainGet('user@domian.com')

'domian.com'

In [241]:
def domainGet(var):
    print (var[5:])

In [242]:
domainGet('user@domian.com')

domian.com


In [247]:
def domainGet(email):
    return email.split('@')[1]

In [248]:
domainGet('user@domain.com')

'domain.com'

In [249]:
def findDog(s):
    return 'dog'in s.lower().split()

In [250]:
findDog('Is there a dog here?')

True

In [251]:
s = 'Is there a dog here?'

In [252]:
'dog' in s.lower().split()

True

In [253]:
def findDog(s):
    print( 'dog'in s.lower().split())

In [254]:
findDog('Is there a dog here')

True


In [256]:
def countDog(st):
    count=0
    for word in st.lower().split():
        if word=='dog':
            count += 1
    return count
    

In [257]:
countDog('This dog runs faster than the other dog dude')

2

In [259]:
def countTom(st):
    num=0
    for word in st.lower().split():
        if word=='tom':
            num += 1
    return num

In [261]:
countTom('This is tom bag manufacture for tom uses and tom brother')

3

In [262]:
seq = ['soup','dog','salad','cat','great']

In [265]:
list(filter(lambda lst:lst[0]=='s',seq))

['soup', 'salad']

In [266]:
def caught_speed(speed,is_birthday):
    if is_birthday:
        speeding = speed -5
    else:
        speeding = speed
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
        

In [267]:
caught_speed(81,True)

'Small Ticket'

In [268]:
caught_speed(81,False)

'Big Ticket'